sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: S0VRmIac5caogTzfytdhCD2fQB91K+/MCCGL/kDRc/HnV66eKwqlzMa+jgbUTCqTA0KbpJEY7QJI57t2Noz/zdSzruOLlRLIqt/ylMvHQ2eRSOLLRkL+1D3NJWoYdW5r6+1RLoBo9BoQyessO2tdVwns5poAxtt+dpmjEooX4Res9OeIfiaZs8RxQwnUoiPg4zionbTiXGtbppJ5iFPIkBJg3FSbOREFfOZFIPvzBSUUgmSdKPkXP3D5ATVI3KcsfE4kM/bwkZsaycVryZHQcSGPMSERI9wslQPVWhrCgo/YVoNDilKZY4dR0WqEydC4xsyfkEbvNZS8l7BtO8HXBLsGqkYUZroTrS631jLKYVLmF0TUjJ1iyBTbZMjGvd4rfUVSmbSG0gfHXxy108P4YW3Sz62FTNB85euey08WBmSsv9K2T/ufhr35CXlcAuguSoRhtrksGKKStvNPdxtFjYJVOBd+GXAd/VeoHDd9Jq76SwrEYt/lGeEm29wkunODyDcY4q0RyjJmlQ9l6fjH4o8g73xndeGOvLzK2OK68vffmcQ8XspPZqEo5JbQcUkBio2UMbX5QaLGhG9YzTj3/QvmYlSGHhJRL3q8/+bRdC4TZvFYpWnC9WdvQRJp31QGkL+ljZC9CHoOIORPdgCC3BgZlfMu8ur42dt2P3bEAg8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Jeanne-D-Arc--Her-Life-And-Death_2553
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy